parameters:
    #parameter_name: value

services:
    app.form.flow.poll:
        class: AppBundle\Form\PollFlow
        parent: craue.form.flow
    app.service.image_uploader:
        class: AppBundle\Service\FileUploader
        arguments:
            - '%uploads_directory%'
    app.factory.poll_factory:
        class: AppBundle\Factory\PollFactory
        arguments:
            - '@doctrine.orm.default_entity_manager'
    app.service.poll_manager:
        class: AppBundle\Service\PollManager
        arguments:
            - '@app.service.image_uploader'
            - '@doctrine.orm.default_entity_manager'
